### ISSUE TITLE
Unable to build stylus with babel 6.

### ISSUE THREAD

**Issue by bencripps** [jbwyme/babel-plugin-stylus-compiler#1]
Command I'm running:

`babel ./src --out-dir dist --presets react --plugins babel-plugin-stylus-compiler`

Error Received: 

`TypeError: src/components/Grid.jsx: Cannot read property 'local' of undefined`

It's failing on this line inside `Grid.jsx`,  `import './../style/main.styl';`

Line failing in `babel-plugin-stylus-compiler/index.js`

`var id = node.specifiers[0].local.name;`

`node.specifiers` is an empty array here. Am I missing some config? 

Thanks!

**Comment by bencripps** [comment]
This fixes my issue: 

`import style from './../style/main.styl';` 

Since the plugin now has an identifier, it parses the final value as `var style =` which makes sense. I'm OK with closing this issue, but I think it's a pretty common pattern to import `.styl` files without declaring them as variables. Perhaps the plugin could simply default to some other variable is present. Anyway, it's up to you. Thanks!

I do have a question, however.

How does this `string` get added as an inline style? Do I need to be using another `babel-plugin`?

**Comment by jbwyme** [comment]
You bring up a good point. My use-case here was to use it with https://github.com/mixpanel/panel which accepts a `css` variable. However, I could modify this plugin to inline the style if no import variable is defined.

**Comment by jbwyme** [comment]
I guess the question is, would it be a sensible default to expect the DOM to be available at execution time and to inject `<style>` tags in with the source? Another alternative here would be to just show an error if someone tries to import without a variable.

**Comment by bencripps** [comment]
I think that's a valid question -- but if a developer knows that there may not be DOM at execution time, they could simply use a variable. I think it's reasonable to expect that if someone is importing style without a variable declaration, then it should be appended to the DOM.

**Comment by jbwyme** [comment]
Alright want to take a look at this? https://github.com/jbwyme/babel-plugin-stylus-compiler/pull/2/files

**Comment by bencripps** [comment]
Looks awesome! Like that the plugin will now handle style as a `var` and as a method of injecting style into the DOM.

Tests looks good as well. Once merged into master, I can run it against my own build and confirm that it works in the real world.

Thanks again!

**Comment by jbwyme** [comment]
Ok merged and published, lmk if it works as expected for you!

**Comment by bencripps** [comment]
Works great!
